### ISSUE TITLE
Hidden::form doesn't set "name" attribute

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#11]
I have been try

`Hidden::form("name") and Hidden::form("name")->name("anyname")`

But it only create

`<input type="hidden" value=""/>`

Without name= attribute , this input will not sent value when submit

**Comment by kompo** [comment]
You should set a value to it like this: 

`_Hidden('parent_id')->value(1)`

This will add {parent_id: 1} in the submitted FormData.

You can also use any model attributes if you are **editing** for example:

`_Hidden('parent_id')->value($this->model->parent_id)`

You can also use route parameters, like this:

`_Hidden('parent_id')->value($this->parameter('parent_id'))`

Alternatively, if you are using an Eloquent Form (i.e. linked to a Model), you may fill in your model's attribute in the beforeSave method and **not even have to use the Hidden komponent**. For example:

```
class ArticleForm extends Form
{
    public $model = Article::class;

    public function beforeSave()
    {
        $this->model->parent_id = $this->parameter('parent_id');
    }

    public function komponents()
    {
        return [
            _FlexBetween(
	        _Title('Manage building'),
	        _SubmitButton('Save')
            ),
            _Input('Name')->name('name'),
            _Select('Type')->name('articleType')->optionsFrom('name', 'id'),
        ];
    }
}
```
