### ISSUE TITLE
Uncaught ReferenceError: toggleMenu is not defined at HTMLDivElement.onclick ((index):178)

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#12]
Hi @kompo ,

I using CollapseOnMobile::leftMenu() but when click hambuger menu button on mobile it cannot toggle menu and fire an error like below

```
Uncaught ReferenceError: toggleMenu is not defined
    at HTMLDivElement.onclick ((index):178)
```

**Comment by kompo** [comment]
Hi, I went another direction with this. CollapseOnMobile has been deprecated in commit [https://github.com/kompo/kompo/commit/21003a54ebb6dbdf3a6d68953b9430cebe8a8e4d](https://github.com/kompo/kompo/commit/21003a54ebb6dbdf3a6d68953b9430cebe8a8e4d) and will be removed in next version. 

I will update the examples on kompo.io website.

In the meantime:
For displaying left and right menus, you may use _FlexBetween().
For displaying sidebar on mobile, please use the new _SidebarToggler().

Let me know if you have questions
