### ISSUE TITLE
Cannot filter() on MultiSelect field ?

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#13]
Hi @kompo ,

I building filter fields on a Kompo Query but face a problem (i don't know it's bug or not) : Cannot filter() on MultiSelect field

For example, I using query UsersRolesPermissionsQuery (copy from here https://kompo.io/library/permissions)
When I using Select for filter , it working properly, Query has been updated follow filter Select value
`Select::form('Filter by Permissions')->name('roles.permissions')->optionsFrom('id','name')->filter(),`
But when I tried
`MultiSelect::form('Filter by Permissions')->name('roles.permissions')->optionsFrom('id','name')->filter(),`
and select multiple values . 
Query not update. I inspect request and find out that Select will send variable like permissions: value , but multiselect will send permissions[0]: value .

Thanks in advance,

**Comment by kompo** [comment]
Before I look into this any further, can you update your kompo package to the latest version and try again?

I fixed a bug on Apr 21st related to that: [https://github.com/kompo/kompo/commit/cd7acc46f4ed894ac2ef6fd8ab0793106f0a03fa](https://github.com/kompo/kompo/commit/cd7acc46f4ed894ac2ef6fd8ab0793106f0a03fa)

If it solves your problem, please close this issue. Otherwise, let me know and I will investigate

**Comment by xnohat** [comment]
Confirm this bug fixed in tag v1.1.1 , thanks for your support.

**Comment by xnohat** [comment]
Hi @kompo ,

Can you public method below or make it become a part of  KompoFormRequest ? 
In my use case, I need to save form data to model by my self , value from MultiSelect must process through this method to available for using or them will in form "tags[0]" "tags[1]", not arrays


$this->parseArrayParametersInRequest(request()->all());

```
protected static function parseArrayParametersInRequest($initialRequestData)
    {
        $parsedArrayParameters = [];
        parse_str(http_build_query($initialRequestData), $parsedArrayParameters);

        return collect(array_merge($initialRequestData, $parsedArrayParameters))->filter(
            fn($v, $key) => strpos($key, '[') === false
        )->all();
    }
```

**Comment by kompo** [comment]
I made it **public** so you can use it in KompoFormRequest.

But I find it weird that you are encountering this issue for a Form submit. Normally, laravel does a good job parsing the parameters with []. Can you share your Form class?

PS: parsing the request with this method is only necessary for these actions: `->browse`, `->filter` & `->refresh`

**Comment by xnohat** [comment]
This apart of my form class for you can understand my use case


```
public function komponents()
	{
		return [
                    ...
                    MultiSelect::form('Tags')->name('tags')->id('tags')
                                    ->optionsFrom('name','name')
                                    ->searchOptions(1, 'searchTags'),
                    ...
                    ];
          }

public function FormSave(KompoFormRequest $request) {
        //Pre-Process Request data for MultiSelect value to Arrays
        $request = $request->replace(static::parseArrayParametersInRequest($request->all() ?? []));

        $data = $request->only($this->model->getFillable());

        $saved = $this->model->fill($data)->save();

        //Tags : tagging save to model
        if($request->has('tags') ){
            //dd($request->input('tags'));die();
            $this->model->syncTagsWithType($request->input('tags'),'article');
        }

        if($saved == true){
            return [
                Input::form('articleid')->name('id')->id('id')->value($this->model->id)->readOnly()->style('width: 88px;'),
                Alert::form('Saved Article with ID: '.$this->model->id)->class('vlAlertSuccess')->icon('icon-check'),
            ];
        }else{
            return [
                Input::form('articleid')->name('id')->id('id')->value('')->readOnly()->style('width: 88px;'),
                Alert::form('Please correct the errors in the Form.')->class('vlAlertError')->icon('icon-attention'),
            ];
        }

    }

    public static function parseArrayParametersInRequest($initialRequestData)
    {
        $parsedArrayParameters = [];
        parse_str(http_build_query($initialRequestData), $parsedArrayParameters);

        return collect(array_merge($initialRequestData, $parsedArrayParameters))->filter(
            fn($v, $key) => strpos($key, '[') === false
        )->all();
    }
```

**Comment by kompo** [comment]
This is weird because you shouldn't need to parse any array parameters on a Form submit... For example: 

```
class TestForm extends Form
{
    public function handle()
    {
        dd(request()->all());
    }

    public function komponents()
    {
        return [
            _MultiSelect()->name('tags')->options([
                  1=>'Tag 1',
                  2=>'Tag 2',
            ]),
            _SubmitButton(),
        ];
    }
}
```
The result is already an array:

![image](https://user-images.githubusercontent.com/58952986/118052848-7b763780-b351-11eb-991b-2de768d3f8a1.png)

Maybe before your method `FormSave` is called, you do something to the request? I don't know. 
I just wanted to let you know. If you have any more questions, let me know! :)
