### ISSUE TITLE
Call to undefined method Kompo\\Database\\CollectionQuery::handleSort()

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#14]
Hi @kompo , 

I have been pull newest kompo package but got an error 

```
Call to undefined method Kompo\\Database\\CollectionQuery::handleSort()
```

When use 

```
Th::form('updated_at')->sort()
```

Thank in advance,

**Comment by kompo** [comment]
Yes sort functionality was missing on Collection Queries. I added it in commit [https://github.com/kompo/kompo/commit/2ac5b79a63e07b266c2390ed23b72d4afcbe232d](https://github.com/kompo/kompo/commit/2ac5b79a63e07b266c2390ed23b72d4afcbe232d).

But make sure to use it like this:

```
Th::form('Update date')->sort('updated_at')
```
or this way for DESC sort
```
Th::form('Update date')->sort('updated_at:DESC')
```
