### ISSUE TITLE
How we can add plugin to kompo-ckeditor ? 

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#16]
Hi @kompo ,

I need some more buttons function in CKEditor Toolbar like Find/Replace.
How can I add plugin to kompo-ckeditor ? or clone and create my own version of kompo-editor ?

Thanks,

**Comment by kompo** [comment]
I can't find the plugin you are talking about in the list of plugins of CKEditor 5.

Yes, unfortunately at the moment, if you want to add a plugin that does not exist in kompo's build, you have to create your own version of kompo-editor

The current supported plugins are: 

[
	Essentials,
	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	Underline,
	BlockQuote,
	CKFinder,
	EasyImage,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TextTransformation,
	Font,
	Mention,
	Alignment
]

**Comment by xnohat** [comment]
For building new CKEditor Build for Kompo could you guide me some steps ?

I have check that you have these packages for CKEditor 5 ?
ckeditor5-build-kompo
kompo-ckeditor
@ckeditor/ckeditor5-vue

**Comment by kompo** [comment]
Hi you can copy how I did it in ckeditor5-build-kompo.
Then you can create your own kompo-ckeditor/komponents/CKEditor.vue and use the mixin CKEditor.js in kompo-ckeditor/mixins/CKEditor.js to get all the methods of kompo.
