### ISSUE TITLE
Security consider in Query Komposer

### ISSUE THREAD

**Issue by xnohat** [kompo/kompo#17]
Hi,

This not bug report but security consider notes. I have got that Kompo will sent all columns of a model in Query to **client side** if we query all data form model.

```
public function query()
    {
        return Article::orderBy('created_at', 'DESC');
    }
```

We need to specify list of columns we need get when build query, exclude sensitive columns data from query.

```
 public function query()
    {
        return Article::select('id','coverimage','title','opinion','shorted_content','slug','source_url','created_at','updated_at')->orderBy('created_at', 'DESC');
    }
```

**Comment by kompo** [comment]
Yes, that is a good point. I had to include the attributes for special queries (like CalendarMonth, Kanban, etc...). But they are not needed for the other layouts (99% of cases). 

I have just pushed a commit that auto-hides all attributes except 'id' in [https://github.com/kompo/kompo/commit/016bce000dccea438e17442918f897adf8b02872](https://github.com/kompo/kompo/commit/016bce000dccea438e17442918f897adf8b02872)

I will think of another way to protect the id, but we need it for now for setting active index...
