### ISSUE TITLE
💡 Add accordion component

### ISSUE THREAD

**Issue by jechaviz** [kompo/kompo#20]
Just like this:
https://vuejsexamples.com/a-customizable-collapsible-panel-accordion-library-built-using-vue3/

Thank you.

**Comment by kompo** [comment]
Hi @jechaviz 

Doesn't the [Collapse component](https://kompo.io/component-api/Collapse) already do that? 

Feel free to reopen the issue, if you have a use case that is not already included in the `_Collapse`
