### ISSUE TITLE
💡 Add radio input also

### ISSUE THREAD

**Issue by jechaviz** [kompo/kompo#25]
Currently radio can be only buttons, can you also create some classical radio option?
Or they are already created? Horizontal and vertical layouts would be good.
Thank you.

**Comment by kompo** [comment]
Hi, I just added the radio input komponent in `Kompo/Radio` and the helper `_Radio()`.

There are 3 special configurations `horizontal()`, `optionClass()` and `optionLabelClass()`.

Let me know if it's working for you or if you have any other ideas for configuring the komponent.
