### ISSUE TITLE
addLabel in selectupdatable not showing well

### ISSUE THREAD

**Issue by jechaviz** [kompo/kompo#26]
After update kompo, i got this problem:
![image](https://user-images.githubusercontent.com/6210208/141860776-d59de7e2-5f77-4fba-b784-e314bf565526.png)
This is the code for the first selectupdatable with the problem
```
_SelectUpdatable('Company')->options([
              '1' => _Columns(
                      _Html('Company 1 Inc.')->col('col-10'),
                      _Html('TaxId1')->col('col-2')
                    ),
              '2' => _Columns(
                      _Html('Company 2 Inc.')->col('col-10'),
                      _Html('TaxId2')->col('col-2')
                    )
            ])->default('1')
              ->addLabel('New company')->col('col-8'),
```

**Comment by kompo** [comment]
Hey, have you updated the front-end `vue-kompo` too?

**Comment by jechaviz** [comment]
Thank you for the prompt response. I tried to update it adding it with composer, but it doesn't recognize the package, so what would be the manual steps to do it? Thank you.

**Comment by kompo** [comment]
At the moment, the most up-to-date releases are:

1- For backend package:
Make sure you have this in your `composer.json`: 
```
"kompo/kompo": "^2.0",
```
then run `composer update`. 

2- For the frontend package:
Make sur you have this in your `package.json`:
```
"vue-kompo": "^2.2.6",
```
and run `npm update` then `npm run dev`.

**Comment by jechaviz** [comment]
solved! Thx a lot! My problem was I was trying to run the vue-compo as composer package, not as node package. Once I moved it to package.json, it worked smootly.
