### ISSUE TITLE
💡 Add a ->role('role')->can[Action]() to each component

### ISSUE THREAD

**Issue by jechaviz** [kompo/kompo#27]
Just imagine like this: myComponent()->role('admin')->canRead()->canEdit()->canUpdate()->canDelete()-->canBrowse()
or easier myComponent()->role('admin')->can('CRUDB'), where any letter is a  initial of the action permited.
default behavior:
myComponent()->role('any')->can('CRUDB')

**Comment by kompo** [comment]
Very interesting idea. It will make things easier to read indeed.

Just to make sure, so if the condition is true, nothing happens and if it is false, we return null (and the component will not display)?

**Comment by jechaviz** [comment]
Well, don't know exactly how to implement it in code, but idea is pretty clear. If myComponent()->can('CRU') it can do almost everytthing, except delete or browse.

**Comment by kompo** [comment]
Hi, I just added an implementation that made sense to me. Here is the commit [https://github.com/kompo/kompo/commit/92b8307b7fdcced1f2bbe8198acbf5219675c4e5](https://github.com/kompo/kompo/commit/92b8307b7fdcced1f2bbe8198acbf5219675c4e5)

There are 2 added methods `role` and `can`. What they do is check if the user is authenticated and has the role/permission, then:

- If he does, all good nothing happens
- If not, null is returned i.e. the element will neither display, nor be used in any submit.

Other things to know:
- To use the role method, you have to define in your User model a `hasRole($role)` method.
- The `can` method follows [Laravel policies](https://laravel.com/docs/8.x/authorization#creating-policies)

Another thing that might interest you. I see you would like to create for example `canRead` or `can('CRUDB')` methods. This is very specific to you, so I would recommend the **powerful feature of macros**. Just add this code to a **helper** file in your app and you will be able to use them exactly the way you intend:

```
\Kompo\Elements\Element::macro('canRead', function(){
    //write your implementation here
});
```

Let me know if you have any questions
